services:
  foodGetAboutIt_api:
    platform: linux/arm64
    image: api:v1
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      # ConnectionStrings__FoodGetItDb: "Host=ep-lively-sound-agm569ne-pooler.c-2.eu-central-1.aws.neon.tech; Database=foodgetitDb; Username=neondb_owner; Password=npg_wMkRbnf45NgP; SSL Mode=VerifyFull; Channel Binding=Require;"
      # ConnectionStrings__foodGetItDb: "Host=localhost;Port=5432;Database=fooddb;Username=postgres;Password=devpass"
      ConnectionStrings__FoodGetItDb: "Host=foodgetaboutitdb.c7480m0omz45.eu-north-1.rds.amazonaws.com;Port=5432;Database=postgres;Username=foodGetIt;Password=Danpel19?71x"
